name: QuantumDungeons
version: '${version}'
main: me.xemor.quantumdungeons.QuantumDungeons
api-version: 1.19
commands:
  start:
    description: /start
    permission: quantumdungeons.start
softdepend:
  - EnchantedCombat